#!/bin/bash

function DecryptString() {
	# Usage: ~$ DecryptString "Encrypted String" "Salt" "Passphrase"
	echo "${1}" | /usr/bin/openssl enc -aes256 -d -a -A -S "${2}" -k "${3}"
}

jamfUser=""
jamfPass=$(DecryptString $5 'salt' 'passphrase')
jamfURL=""

#Get the serial number
serialNumber=$(system_profiler SPHardwareDataType | grep Serial | awk '{ print $4 }')

#Group ID and Name to add device to
groupID=""
groupName=""

xmlHeader="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>"
apiData="<computer_group><id>${groupID}</id><name>$groupName</name><computer_additions><computer><serial_number>$serialNumber</serial_number></computer></computer_additions></computer_group>"

#Add Computer to Static Group
/usr/bin/curl -sk \
--user "$jamfUser":"$jamfPass" \
--header "Content-Type: text/xml" \
-d "${xmlHeader}${apiData}" \
--request PUT \
$jamfURL/computergroups/id/$groupID

